-- Scripts das tabelas utilizadas

-- Instância CampanhasPublicitarias
CREATE TABLE TGFCAMPANHA (
    CODCAMP NUMBER(10) PRIMARY KEY,
    DESCRICAO VARCHAR2(20),
    ATIVO CHAR(1),
    DTINI DATE,
    DTFIN DATE,
    VLRASSINATURA NUMBER(18,2),  
    STATUS CHAR(1),
    CODEMP NUMBER(10),
    CODPARC NUMBER(10),
    CONSTRAINT FK_CAMP_EMP FOREIGN KEY (CODEMP) REFERENCES TGFEMP(CODEMP),
    CONSTRAINT FK_CAMP_PAR FOREIGN KEY (CODPARC) REFERENCES TGFPAR(CODPARC)
);


-- Instância FinanceiroCampanha
CREATE TABLE TGFCAMPFIN(
ID NUMBER(10),
CODCAMP NUMBER(10),
VLRTOT NUMBER(18,2),
VLRMULTA NUMBER(18,2),
DTVENC DATE,
DTREFERENCIA DATE,
CONSTRAINT PK_CODCAMP PRIMARY KEY (ID,CODCAMP)
);