/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.campanhaspublicitarias.services;

/**
 * Remote interface for CampanhasSP.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface CampanhasSP
   extends javax.ejb.EJBObject
{

   public void inserirAssinatura( br.com.sankhya.ws.ServiceContext sctx )
      throws java.rmi.RemoteException;

   public void aplicarMulta( br.com.sankhya.ws.ServiceContext sctx )
      throws java.rmi.RemoteException;

   public void duplicarAssinatura( br.com.sankhya.ws.ServiceContext sctx )
      throws java.rmi.RemoteException;

}
