/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.campanhaspublicitarias.services;

/**
 * Home interface for CampanhasSP.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface CampanhasSPHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CampanhasSP";
   public static final String JNDI_NAME="br/com/campanhaspublicitarias/services/CampanhasSP";

   public br.com.campanhaspublicitarias.services.CampanhasSP create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
